version: "3.3"

services:

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  harmony-osu-server:
    image: harmony-osu-server:latest
    ports:
      - 10000:${APP_PORT}
    environment:
      - APP_ENV=${APP_ENV}
      #TODO make localhost postgres in env
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - DB_SCHEME=${DB_SCHEME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      
